name: simple-dev
version: 1.0.0
summary: Simple Dev Environment
description: Minimal Terraform ADE definition
runner: mcr.microsoft.com/azure-dev-center/terraform:latest
templatePath: main.tf

parameters:
  - id: envName
    name: Environment Name
    type: string
    required: true
