name: vm-dev
version: 1.0.0
summary: Simple Dev Environment
description: Minimal ADE definition (VNET)
runner: Bicep
templatePath: main.bicep

parameters:
  - id: envName
    name: Environment Name
    description: Used as a prefix for deployed resources
    type: string
    required: true

  - id: vnetName
    name: VNET Name
    description: Name of the virtual network
    type: string
    required: true

  - id: vnetAddressPrefix
    name: VNET Address Space
    description: CIDR for VNET (example: 10.10.0.0/16)
    type: string
    required: true

  - id: subnetName
    name: Subnet Name
    description: Name of the subnet
    type: string
    required: true

  - id: subnetAddressPrefix
    name: Subnet Address Prefix
    description: CIDR for subnet (example: 10.10.1.0/24)
    type: string
    required: true
