name: vm-dev
version: 1.0.0
summary: Simple Dev Environment
description: Minimal ADE definition (VNet + Subnets)
runner: Bicep
templatePath: main.bicep

parameters:
  - id: envName
    name: Environment Name
    type: string
    required: true

  - id: location
    name: Location
    type: string
    required: false

  - id: vnetName
    name: VNet Name
    type: string
    required: false

  - id: vnetAddressSpace
    name: VNet Address Space
    type: string
    required: true

  - id: subnets
    name: Subnets
    type: array
    required: true

  - id: dnsServers
    name: DNS Servers
    type: array
    required: false

  - id: tags
    name: Tags
    type: object
    required: false
