name: WebApp
version: 1.0.0
summary: Azure Web App Environment
description: Deploys a web app in Azure without a datastore
runner: "acrtfoliver.azurecr.io/ade-terraform-runner:1.0.0"
templatePath: azuredeploy.tf

# 実行時に使用するパラメータ
parameters:
  - id: db_password
    name: db_password
    description: 'The password for the database'
    type: string
    required: true
