name: RGOnly
version: 1.0.0
summary: Resource Group Environment
description: Deploys a resource group only
runner: "acrtfoliver.azurecr.io/ade-terraform-runner:1.0.0"
templatePath: azuredeploy.tf

parameters:
  - id: resource_group_name
    name: Resource Group Name
    type: string
    required: true

  - id: location
    name: Location
    type: string
    required: true
