  - id: storage_account_tier
    name: Storage Account Tier
    type: string
    required: false
    default: "Standard"

  - id: storage_account_replication_type
    name: Storage Account Replication Type
    type: string
    required: false
    default: "LRS"

  - id: storage_account_kind
    name: Storage Account Kind
    type: string
    required: false
    default: "StorageV2"
